In [47]:
#Create numpy
import numpy as np
lst = [1,2,"string",4]
arr = np.array(lst)
print(arr.dtype)

<U11


In [7]:
"""
Size Comparison of ndarray and list objects
"""
import numpy as np
from sys import getsizeof

lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

168
160


In [10]:
"""
Operations with Numpy Arrays
"""
prices = [30,25,40,20,20,35,50,35]

new_prices = [price-5 for price in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [40]:
import numpy as np
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])
test_3_fixed = test_3+2

total_grade = test_1+test_2+test_3
print(total_grade)
final_grade = total_grade/3
print(final_grade)

jeremy_test_2 = test_2[3]
manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)
arr = np.array([test_1,test_2,test_3])
print(arr)
print(arr[:,-1])
mask = arr > 90
print(mask)

[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
[87 91 92]
[[ True  True False  True False]
 [False  True False  True  True]
 [False False False False  True]]


In [2]:
"""
Logical Operations with Arrays
"""
#masking
a = np.array([1,2,3,4,5,6,7,8,9,10])
mask = a>5
print(mask)

#selected
selected = a[a>5]
print(selected)

#combined logical operations | &
selected = a[(a > 6)  | (a < 4)]
print(selected)

NameError: name 'np' is not defined

In [15]:
"""
Goldilocks Porridge Festival
"""
import numpy as np
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[porridge > 60 & porridge < 80]
print(just_right)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()