In [16]:
import numpy as np

"""
Creating a Numpy
"""
my_list = [1,2,3,4,5,6]
my_array = np.array(my_list)
print(my_array)
my_arr = np.array([1,2,3,4,5,6])
print(my_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [17]:
"""
Operations with Numpy Arrays
"""
prices = [30,25,40,20,20,35,50,35]
new_prices = [price-5 for price in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [19]:
"""
Operation with Test Scores
"""
import math
#1
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

#2
test_3_fixed = test_3 + 2

#3
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade/3
print(final_grade)

[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [35]:
#4
jermy_test_2 = test_2[3]
manual_adwoa_test_1 = [test_1[1],test_1[2]]

#5
student_scores = np.array([test_1,test_2,test_3])
print("Tanya:", arr[2,0])
print("Cody:",arr[:3,4])

Tanya: 87
Cody: [87 91 92]


In [42]:
"""
Logical Operations with Arrays
"""
a = np.array([1,2,3,4,5,6,7,8,9,10])
mask = a>5
print(mask)

selected = a[a>5]
print(selected)

selected = a[(a>5)|(a<3)]
print(selected)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 1  2  6  7  8  9 10]


In [44]:
"""
Goldilocks Porridge Festival
"""
import numpy as np
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
print(cold)
hot = porridge[porridge > 80]
print(hot)
just_right = porridge[(porridge > 60) & (porridge < 80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
