In [48]:
"""
Creating an array
"""
import numpy as np

a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [49]:
"""
Random array
"""

np.random.seed(10)
b = np.random.randint(10,size=(3,4,5))
print(b)

[[[9 4 0 1 9]
  [0 1 8 9 0]
  [8 6 4 3 0]
  [4 6 8 1 8]]

 [[4 1 3 6 5]
  [3 9 6 9 1]
  [9 4 2 6 7]
  [8 8 9 2 0]]

 [[6 7 8 1 7]
  [1 4 0 8 5]
  [4 7 8 8 2]
  [6 2 8 8 6]]]


In [50]:
"""
NumPy Array Attributes
"""
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

3
(3, 4, 5)
60
int32
4
240


In [51]:
"""
Views
"""
np.random.seed(1)
arr = np.random.randint(10,size=(2,4))
print(arr)
arr_sub = arr[:2,:2]
print (arr_sub)
arr_sub[0,0] = 16
print (arr_sub)
print(arr)

[[5 8 9 5]
 [0 0 1 7]]
[[5 8]
 [0 0]]
[[16  8]
 [ 0  0]]
[[16  8  9  5]
 [ 0  0  1  7]]


In [85]:
"""
Array Slicing
"""
arr = np.arange(10)
print(arr)
print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])


[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [89]:
arr_2 = arr[np.newaxis, :]
print(arr_2)
arr_sub = arr_2[:2,:2].copy()
print (arr_sub)
arr_sub[0][0] = 1
print(arr_sub)
print(arr)
arr_a = arr_2.reshape(5,2)
print(arr_a)

[[0 1 2 3 4 5 6 7 8 9]]
[[0 1]]
[[1 1]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [90]:
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)
print(arr.shape)

arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.ndim)
print(arr_new.shape)

[1 2 3]
1
(3,)
[[1 2 3]]
2
(1, 3)


In [91]:
arr_new = arr[:, np.newaxis]
print(arr_new)
print(arr_new.ndim)
print(arr_new.shape)

[[1]
 [2]
 [3]]
2
(3, 1)


In [96]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])
arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
arr_4 = np.arange(10)
arr_1, arr_2, arr_3 = np.split(arr_4, [3, 5])
print(arr_1)
print(arr_2)
print(arr_3)

[0 1 2]
[3 4]
[5 6 7 8 9]
