In [2]:
is_tested = True
is_passed = False
print(type(is_tested))

<class 'bool'>


In [4]:
print("Yes" == "Yes")
print((2>1)==(5<10))
c = '2'
d = 2
print(c==d)

True
True
False


In [8]:
print("Yes" != "No")
print(10 != 20)
print((10>1) != (10>1000))

True
True
True


In [15]:
puppy = "maltese"
is_yes = False
if puppy == "maltese":
    is_yes =True
elif puppy == "poodle":
    is_yes = True
elif puppy == "shihtzu":
    is_yes = True
print(is_yes)

True


In [26]:
list_ex = [1,2,3,4,5,6,7]
list_ex_2 = list_ex[0:4]
print(list_ex_2)
list_ex_2[0] = 3
print(list_ex_2)
print(list_ex)

[1, 2, 3, 4]
[3, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7]


In [44]:
sublist_index=[[1,2],[3,4],[5,6]]
print(sublist_index)
print(sublist_index[0][1])
print(sublist_index.count([1,3]))

[[1, 2], [3, 4], [5, 6]]
2
0


In [53]:
sublist_index.append([7,8])
print(sublist_index)
sublist_index.insert(1,[9,10])
print(sublist_index)
tolist = [6,5,4,3,2,1]

print(tolist)
totolist = sorted(tolist)
print(totolist)

[[1, 2], [9, 10], [9, 10], [9, 10], [9, 10], [9, 10], [3, 4], [5, 6], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8]]
[[1, 2], [9, 10], [9, 10], [9, 10], [9, 10], [9, 10], [9, 10], [3, 4], [5, 6], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8], [7, 8]]
[6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6]


In [55]:
nums = [1,2,3,4,5]
for num in nums:
    print(num)

1
2
3
4
5


In [57]:
for i in range(4):
    print(i)

0
1
2
3


In [59]:
for i in range(4):
    print("Warning!")

Warning!
Warning!
Warning!
Warning!


In [61]:
for num in nums:
    if num<0:
        continue
    print(num)

1
2
3
4
5


In [64]:
game_plays = ['stage1','gameover','stage3','stage4','stage5','stage6']
for play in game_plays:
    if play == 'gameover':
        print("Game is over...")
        break
    print(play + "is complete.")

stage1is complete.
Game is over...


In [66]:
one_to_ten = [i+1 for i in range(10)]
print(one_to_ten)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [68]:
hotspurs = [['손흥민', 'A+'],['해리케인','F'],['은돔벨레','F']]
poors = [player[0] for player in hotspurs if player[1] ==  'F']
print("혼날 사람:")
print(poors)

혼날 사람:
['해리케인', '은돔벨레']


In [70]:
one_to_nine = [i+1 for i in range(9)]
for i in one_to_nine:
    for j in one_to_nine:
        print("%d X %d = %d" %(i,j,i*j))

1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81


In [73]:
hungry = True
foods_on_table = ['a','b','c','d','e']
foods_num = 7
ate_num = 0

while ate_num <4:
    print(foods_on_table[ate_num]+"냠냠")
    ate_num +=1
print("gg..")

a냠냠
b냠냠
c냠냠
d냠냠
gg..


In [76]:
x = 1
y = 1
while x<10:
    print("Do")
    x+=1
    y+=1
    if y>5:
        print("why")

Do
Do
Do
Do
Do
why
Do
why
Do
why
Do
why
Do
why


In [79]:
def fahr_to_celsius(temp):
    return ((temp - 32) *(5/9))

print(fahr_to_celsius(50))

10.0


In [81]:
# Define a function
def my_function(x):
    return x + 1

print(my_function(1))
# invoke the function
x = 1
print(my_function(x))
# invoke the function

2
2


In [85]:
# Define a class
class my_class:
    def my_method(self):
        return x + 1
    
cls = my_class()
# create an instance

x = 2
print(cls.my_method())
# invoke the method

3


In [87]:
def introduce_myself(name, birthyear, city):
    print("Hello everyone, my name is %s, I was born in %d, and I live in %s." % (name, birthyear, city))

introduce_myself("Hyun Ahn", 1985, "Anyang")

Hello everyone, my name is Hyun Ahn, I was born in 1985, and I live in Anyang.


In [90]:
import numpy as np
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [92]:
prices = [30, 25, 40, 20, 20, 35, 50, 35]
new_prices = [price-5 for price in prices]
print(new_prices)

[25, 20, 35, 15, 15, 30, 45, 30]


In [94]:
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25 20 35 15 15 30 45 30]


In [96]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
selected = a[a > 5]
print(selected)

[10  9  8  9  7]


In [99]:
selected = a[(a > 5) | (a < 3)]
print(selected)

[10  2  2  9  8  9  7]


In [102]:
x = np.arange(4)
print(x)

[0 1 2 3]
