In [2]:
23Qprint("Hello World")
print(100)
pi = 3.141592
print(pi)

Hello World
100
3.141592


In [3]:
print("Yes" == 'Yes')

True


In [4]:
print((2>1) == (5<10))

True


In [5]:
x=1
y=2
try:
    print(y)
    print(z)
    
except:
    print('[Error]')

2
[Error]


In [6]:
def my_function(x):
    return x + 1
y = 3
my_function(y)

class my_class:
    def my_method(self):
        return x+1

cls = my_class()
x = 2
print(cls.my_method())

3


In [7]:
def check_leap_year(year):
    if year % 4==0:
        return str(year) + "s"
    else:
        return str(year) + 'n'
year_to_check = 2021
returned_value = check_leap_year(year_to_check)
print(returned_value)

2021n


In [8]:
def square_point(x,y,z):
    x = x**2
    y = y**2
    z = z**2
    return x, y, z

x_2,y_2,z_2 = square_point(1,2,3)
print(x_2,y_2,z_2)

1 4 9


In [9]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [10]:
list = [1,2,3,4]
arr = np.array(list)
print(arr)

[1 2 3 4]


In [11]:
print(arr.dtype)

int32


In [12]:
from sys import getsizeof

list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
print(getsizeof(list))

arr = np.array(list)
print(getsizeof(arr))

176
164


In [13]:
prices = [30,25,40,20,20]
arr =np.array(prices)

In [14]:
test_1=np.array([92, 94, 88, 91, 87])
test_2=np.array([79, 100, 86, 93, 91])
test_3=np.array([89, 87, 74, 92, 94])
test_3 = test_3-2

In [15]:
test_3_fixed = test_3+2
print(test_3_fixed)
total_grade = test_1+ test_2 + test_3_fixed
print(total_grade)
print(total_grade/3)

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [16]:
jeremy_test_2 = test_2[3]
print(jeremy_test_2)
manual_adwoa_test_1 = np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

93
[94 88]


In [17]:
student_scores = np.array([test_1,test_2,test_3])
student_scores[1][2]

86

In [18]:
x = np.arange(4)
print(np.add(x,3))

[3 4 5 6]


In [19]:
x = np.array([-2,-1,0,1,2])
print(np.abs(x))

[2 1 0 1 2]


In [20]:
print(np.linspace(0,100,5))

[  0.  25.  50.  75. 100.]


In [25]:
x = np.arange(1,5)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

10
24


In [28]:
accum = np.add.accumulate(x)
print(accum)
accum = np.multiply.accumulate(x)
print(accum)

[ 1  3  6 10]
[ 1  2  6 24]


In [30]:
arr = np.random.rand(10000000)
np.sum(arr)

4998725.978989007

In [32]:
%timeit sum(arr)

718 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%timeit np.sum(arr)

11.8 ms ± 109 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
arr = np.array([[3,6,6,0],[9,8,4,7],[0,0,7,1]])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[12 14 17  8]
[15 28  8]


In [35]:
a = np.array([0,1,2])
print(a+5)
a = np.array([0,1,2])
b = np.array([5,5,5])
print(a+b)

[5 6 7]
[5 6 7]


In [36]:
a = np.ones((3,3))
b = np.arange(3)
print(a+b)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [38]:
a = np.arange(3)
a = a[:, np.newaxis]
b = np.arange(3)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [41]:
x = np.array([1,2,3,4,5])
print(x < 3)
print(x >= 3)

[ True  True False False False]
[False False  True  True  True]


In [42]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [43]:
print(x<6)

[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [45]:
print(np.count_nonzero(x<6))
print(np.any(x>8))
print(np.all(x>1))
print(np.sum(x<6))

8
True
False
8


In [48]:
x = np.array([[5,0,3,3],[7,9,3,5],[2,4,7,6]])
print(x<5)
print(x[x<5])

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


In [50]:
x = np.random.randint(100,size =10)
print(x)
a = x[2]
b = x[4]
c = x[6]
print([a,b,c])
ind = [2,4,6]
print(x[ind])

[37 25 77 72  9 20 80 69 79 47]
[77, 9, 80]
[77  9 80]


In [51]:
x = np.array([[8,8,6,2,8],[7,2,1,5,4],[4,5,7,3,6]])
row = [0,1,2]
col = [2,1,4]
print(x[row, col])

[6 2 6]


In [52]:
row = np.array([0,1,2])
col = np.array([2,1,4])
x[row[:, np.newaxis],col]

array([[6, 8, 8],
       [1, 2, 4],
       [7, 5, 6]])

In [57]:
print(x[2,[2,0,1]])
print(x[1:, [2,0,1]])

[7 4 5]
[[1 7 2]
 [7 4 5]]


In [59]:
import pandas as pd

ser = pd.Series([0.25,0.5,0.75,1.0])
print(ser)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [60]:
arr = ser.values
print(arr)
ind = ser.index
print(ind)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [62]:
ser = pd.Series([0.25,0.5,0.75, 1.0],index=['a','b','c','d'])
print(ser)
print(ser['b'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


In [63]:
dict = {'a':1, 2: 'two','third':True}
print(dict)

{'a': 1, 2: 'two', 'third': True}


In [66]:
population_dict = {'California': 38332521,
'Texas': 26448193,
"New York": 19651127,
'Florida': 19552860,
'Illinois': 12882135}

population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [67]:
print(population['California':'New York'])

California    38332521
Texas         26448193
New York      19651127
dtype: int64


In [68]:
area_dict = {'California': 423967,'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [69]:
states = pd.DataFrame({'population':population,'area':area})
print(states)

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995


In [70]:
print(states.index)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')


In [71]:
states.columns

Index(['population', 'area'], dtype='object')

In [73]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [75]:
arr = np.random.rand(3,2)
print(arr)
arr_df = pd.DataFrame(arr, columns= ['foo','bar'], index=['a','b','c'])
print(arr_df)

[[0.58201979 0.53737323]
 [0.75861562 0.10590761]
 [0.47360042 0.18633234]]
        foo       bar
a  0.582020  0.537373
b  0.758616  0.105908
c  0.473600  0.186332


In [78]:
ser = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
print(ser)
print(ser['b'])
print('a' in ser)
print(0.25 in ser)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5
True
False


In [80]:
print(ser.keys())
ser['e']=1.25
ser['a']=0.125
print(ser)

Index(['a', 'b', 'c', 'd'], dtype='object')
a    0.125
b    0.500
c    0.750
d    1.000
e    1.250
dtype: float64


In [81]:
print(ser['a':'c'])
print(ser[(ser>0.3) & (ser<0.8)])
print(ser[['a','e']])

a    0.125
b    0.500
c    0.750
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.125
e    1.250
dtype: float64


In [82]:
print(ser['a':'c'])
print(ser[0:2])

a    0.125
b    0.500
c    0.750
dtype: float64
a    0.125
b    0.500
dtype: float64


In [86]:
print(states['area'])
print(states.area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


In [99]:
states['density'] = states['population']/states['area']
print(states['density'])

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64


In [90]:
ser = pd.Series(['a','b','c'],index=[1,3,5])
print(ser.loc[1])
print(ser.loc[1:3])
print(ser.iloc[1])
print(ser.iloc[1:3])

a
1    a
3    b
dtype: object
b
3    b
5    c
dtype: object


In [100]:
states.loc[states.density > 100, ['population', 'density']]
print(states.iloc[0,2])
states.iloc[0,2] = 90
print(states.iloc[0,2])

90.41392608386974
90.0


In [101]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

print(np.concatenate([x,y,z]))

[1 2 3 4 5 6 7 8 9]


In [102]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [104]:
def make_df(cols,ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

x = make_df('ABC',[1,2])
print(x)

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [105]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])

pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [106]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

print(pd.concat([df3, df4], axis=1))

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [108]:
x = make_df('ABC',[1,2])
y = make_df('BCD',[3,4])

print(pd.concat([x,y], join = 'outer'))
print(pd.concat([x,y], join = 'inner'))

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [118]:
arr = np.array([['Bob','Acc'],['Jake','Eng'],['Lisa','Eng'],['Sue','HR']])
df1 = pd.DataFrame(arr, columns= ['employee','group'])
print(df1)

  employee group
0      Bob   Acc
1     Jake   Eng
2     Lisa   Eng
3      Sue    HR


In [119]:
df2 = pd.DataFrame(np.array([['Lisa',2004],['Bob',2008],['Jake',2012],['Sue',2014]]), columns= ['employee','hire_date'])
print(df2)

  employee hire_date
0     Lisa      2004
1      Bob      2008
2     Jake      2012
3      Sue      2014


In [122]:
df3 = pd.merge(df1,df2)
print(df3)

  employee group hire_date
0      Bob   Acc      2008
1     Jake   Eng      2012
2     Lisa   Eng      2004
3      Sue    HR      2014


In [126]:
df4 = pd.DataFrame(np.array([['Acc','Carly'],['Eng','Guido'],['HR','Steve']]),columns = ['group','supervisor'])
print(df4)

  group supervisor
0   Acc      Carly
1   Eng      Guido
2    HR      Steve


In [128]:
print(pd.merge(df3,df4))

  employee group hire_date supervisor
0      Bob   Acc      2008      Carly
1     Jake   Eng      2012      Guido
2     Lisa   Eng      2004      Guido
3      Sue    HR      2014      Steve


In [130]:
df5 = pd.DataFrame(np.array([['Acc','math'],['Acc','spr'],['Eng','coding'],['Eng','linux'],['HR','sp'],['HR','org']]),columns = ['group','skills'])
print(df5)

  group  skills
0   Acc    math
1   Acc     spr
2   Eng  coding
3   Eng   linux
4    HR      sp
5    HR     org


In [132]:
print(pd.merge(df1,df5))

  employee group  skills
0      Bob   Acc    math
1      Bob   Acc     spr
2     Jake   Eng  coding
3     Jake   Eng   linux
4     Lisa   Eng  coding
5     Lisa   Eng   linux
6      Sue    HR      sp
7      Sue    HR     org


In [133]:
from datetime import datetime
print(datetime(year=2021, month=11, day=11))

2021-11-11 00:00:00


In [134]:
from dateutil import parser
date = parser.parse("11th of November, 2021")
print(date)

2021-11-11 00:00:00


In [136]:
date.strftime('%A')

'Thursday'

In [138]:
date = np.array('2021-11-11')
print(date)
date = np.datetime64('2021-11-11')
print(date)

2021-11-11
2021-11-11


In [139]:
print(date + np.arange(12))

['2021-11-11' '2021-11-12' '2021-11-13' '2021-11-14' '2021-11-15'
 '2021-11-16' '2021-11-17' '2021-11-18' '2021-11-19' '2021-11-20'
 '2021-11-21' '2021-11-22']


In [140]:
t = np.datetime64('2021-11-11 16:05')
print(t)

2021-11-11T16:05


In [141]:
t = np.datetime64('2021-11-11 16:06:10.20','ns')
print(t)

2021-11-11T16:06:10.200000000


In [144]:
date = pd.to_datetime('11th of November, 2021')
print(date)
print(date+pd.to_timedelta(np.arange(7)))
print(date.strftime('%A'))

2021-11-11 00:00:00
DatetimeIndex([          '2021-11-11 00:00:00',
               '2021-11-11 00:00:00.000000001',
               '2021-11-11 00:00:00.000000002',
               '2021-11-11 00:00:00.000000003',
               '2021-11-11 00:00:00.000000004',
               '2021-11-11 00:00:00.000000005',
               '2021-11-11 00:00:00.000000006'],
              dtype='datetime64[ns]', freq=None)
Thursday


In [145]:
ind = pd.DatetimeIndex(['2021-10-27', '2021-10-28', '2021-10-29', '2021-10-30', 
'2021-10-31', '2021-11-01', '2021-11-02'])

ser = pd.Series([0,1,2,3,4,5,6],index = ind)
print(ser)

2021-10-27    0
2021-10-28    1
2021-10-29    2
2021-10-30    3
2021-10-31    4
2021-11-01    5
2021-11-02    6
dtype: int64


In [146]:
print(ser['2021-10-27':'2021-10-31'])

2021-10-27    0
2021-10-28    1
2021-10-29    2
2021-10-30    3
2021-10-31    4
dtype: int64


In [147]:
print(ser['2021-11'])

2021-11-01    5
2021-11-02    6
dtype: int64


In [148]:
dates = pd.to_datetime([datetime(2015, 7, 3), "4th of July, 2015",'2015-Jul-6','07-07-2015','20150708'])
print(dates)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)


In [149]:
print(dates.to_period('D'))

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]', freq='D')


In [151]:
print(dates.to_period('W'))

PeriodIndex(['2015-06-29/2015-07-05', '2015-06-29/2015-07-05',
             '2015-07-06/2015-07-12', '2015-07-06/2015-07-12',
             '2015-07-06/2015-07-12'],
            dtype='period[W-SUN]', freq='W-SUN')


In [152]:
print(dates - dates[0])

TimedeltaIndex(['0 days', '1 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq=None)


In [153]:
print(pd.date_range('2021-10-27', '2021-10-31'))

DatetimeIndex(['2021-10-27', '2021-10-28', '2021-10-29', '2021-10-30',
               '2021-10-31'],
              dtype='datetime64[ns]', freq='D')


In [154]:
pd.date_range('2021-10-27', periods=5)

DatetimeIndex(['2021-10-27', '2021-10-28', '2021-10-29', '2021-10-30',
               '2021-10-31'],
              dtype='datetime64[ns]', freq='D')

In [156]:
pd.date_range('2021-10-27', periods=12, freq='H')

DatetimeIndex(['2021-10-27 00:00:00', '2021-10-27 01:00:00',
               '2021-10-27 02:00:00', '2021-10-27 03:00:00',
               '2021-10-27 04:00:00', '2021-10-27 05:00:00',
               '2021-10-27 06:00:00', '2021-10-27 07:00:00',
               '2021-10-27 08:00:00', '2021-10-27 09:00:00',
               '2021-10-27 10:00:00', '2021-10-27 11:00:00'],
              dtype='datetime64[ns]', freq='H')

In [157]:
pd.period_range('2021-10', periods=12, freq='M')

PeriodIndex(['2021-10', '2021-11', '2021-12', '2022-01', '2022-02', '2022-03',
             '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-09'],
            dtype='period[M]', freq='M')

In [159]:
pd.timedelta_range(0, periods=10, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='H')

In [161]:
pd.date_range('2021-11-01', periods=10, freq="M")

DatetimeIndex(['2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28',
               '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30',
               '2022-07-31', '2022-08-31'],
              dtype='datetime64[ns]', freq='M')

In [162]:
pd.date_range('2021-11-01', periods=10, freq="BM")

DatetimeIndex(['2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28',
               '2022-03-31', '2022-04-29', '2022-05-31', '2022-06-30',
               '2022-07-29', '2022-08-31'],
              dtype='datetime64[ns]', freq='BM')

In [163]:
pd.date_range('2021-11-01', periods=10, freq="MS")

DatetimeIndex(['2021-11-01', '2021-12-01', '2022-01-01', '2022-02-01',
               '2022-03-01', '2022-04-01', '2022-05-01', '2022-06-01',
               '2022-07-01', '2022-08-01'],
              dtype='datetime64[ns]', freq='MS')

In [164]:
pd.date_range('2021-11-01', periods=9, freq='2H30T')

DatetimeIndex(['2021-11-01 00:00:00', '2021-11-01 02:30:00',
               '2021-11-01 05:00:00', '2021-11-01 07:30:00',
               '2021-11-01 10:00:00', '2021-11-01 12:30:00',
               '2021-11-01 15:00:00', '2021-11-01 17:30:00',
               '2021-11-01 20:00:00'],
              dtype='datetime64[ns]', freq='150T')

In [165]:
from pandas.tseries.offsets import DateOffset
ts = pd.Timestamp('2021-10-31 23:28:30')
print(ts + DateOffset(hours=40))

2021-11-02 15:28:30


In [166]:
ts - DateOffset(years=71, months=4, days=5, hours=19, minutes=28, seconds=30)

Timestamp('1950-06-25 04:00:00')

In [167]:
pip install pandas_datareader

Note: you may need to restart the kernel to use updated packages.
